### ISSUE TITLE
Ningún Escocés Verdadero

### ISSUE THREAD

**Issue by Gorsh2** [jorgebg/falaciaslogicas.com#5]
Hola, encontré recién esta web. Voy a agregar la falacia de "Ningún Escocés Verdadero"; no es una de las clásicas pero es más que relevante por lo extendido de su uso... 

Si me equivoco, editen o borren!

**Comment by jorgebg** [comment]
Muchas gracias @Gorsh2. He añadido un par de keywords a la falacia: de363ca
